export const SETTINGS_COPY = {
  tabs: {
    general: 'Général',
    social: 'Social',
    account: 'Compte',
  },
  legalHeading: 'Informations légales',
  cookiesHeading: 'Cookies',
  cookiesBody:
    "Les cookies nécessaires (session) sont toujours actifs. Les cookies d'analyse ne sont chargés qu'avec votre accord.",
  analyticsLabel: "Cookies d'analyse",
  analyticsHint: "Mesure d'audience (aucun script tiers pour l'instant)",
  analyticsAria: "Active ou désactive les cookies d'analyse optionnels.",
  reopenBanner: 'Rouvrir le bandeau cookies',
  audioHeading: 'Audio',
  audioHint: 'Ce réglage s’applique partout : parties, librairie, aperçus du profil et notifications.',
  muteOn: 'Son coupé',
  muteOff: 'Son activé',
  muteAriaOn: 'Activer le son',
  muteAriaOff: 'Couper le son',
  volumeLabel: 'Volume',
  volumeValue: (n: number) => `${n} %`,
  mutedHint: (n: number) => `Le volume est à ${n} %, mais le son est coupé.`,
  signInToSync: 'Connectez-vous pour retrouver ces réglages sur tous vos appareils.',
  motionHeading: 'Animations',
  motionHint: 'Auto suit le système. Réduit coupe les animations. Complet les force, même si le système les réduit.',
  motionAuto: 'Auto',
  motionReduced: 'Réduit',
  motionFull: 'Complet',
  gameplayHeading: 'En partie',
  autofocusLabel: 'Focus automatique sur la réponse',
  autofocusHint: 'Le champ est sélectionné à chaque nouveau round.',
  submitOnEnterLabel: 'Valider avec Entrée',
  submitOnEnterHint: 'Les flèches et Échap de l’autocomplétion restent actifs.',
  soloAutoRevealLabel: 'Révéler tout de suite en solo',
  soloAutoRevealHint: 'Après l’envoi, le clip et la réponse s’affichent sans attendre le bouton.',
  shortcutReminderLabel: 'Rappel des raccourcis clavier',
  shortcutReminderHint: 'Affiché uniquement sur un appareil avec clavier.',
  notificationsHeading: 'Notifications',
  notificationsHint:
    'Les badges et la liste d’amis restent visibles. Ces options ne concernent que les toasts et les sons.',
  friendRequestVisual: 'Toast pour les demandes d’amis',
  friendRequestSound: 'Son pour les demandes d’amis',
  lobbyInviteVisual: 'Toast pour les invitations',
  lobbyInviteSound: 'Son pour les invitations',
  soundsMutedHint: 'Le son global est coupé : aucun jingle de notification ne sera joué.',
  privacyHeading: 'Confidentialité',
  privacyHint: 'Ces options concernent votre compte, pas la configuration des salons.',
  showFavorites: 'Afficher mes titres favoris sur mon profil public',
  allowFriendRequests: 'Accepter les demandes d’amis',
  statusAudience: 'Qui voit mon statut en ligne',
  historyAudience: 'Qui voit mon historique récent',
  inviteAudience: 'Qui peut m’inviter en salon',
  audienceEveryone: 'Tout le monde',
  audienceFriends: 'Amis',
  audienceNobody: 'Personne',
  historyAudienceHint: 'Les statistiques agrégées restent visibles.',
  blockedHeading: 'Comptes bloqués',
  blockedEmpty: 'Aucun compte bloqué.',
  blockedUnblock: 'Débloquer',
  blockedConfirmTitle: 'Débloquer ce compte ?',
  blockedConfirmBody: (username: string) =>
    `${username} pourra à nouveau voir votre profil et vous envoyer une demande d’ami.`,
  integrationsHeading: 'Listes AniList / MAL',
  integrationsHint: 'Les deux comptes peuvent rester liés. Une seule source est active pour le mode Watched.',
  integrationsManage: 'Gérer dans les paramètres',
  listActive: 'Source active',
  listInactive: 'Lié, inactif',
  listUnlinked: 'Non lié',
  listLink: 'Lier',
  listEdit: 'Modifier',
  listLoading: 'Actualisation des comptes liés…',
  listActiveSource: 'Source active pour le mode Watched',
  listSync: 'Synchroniser',
  listUnlink: 'Délier',
  listUnlinkConfirmTitle: 'Délier ce compte ?',
  listUnlinkConfirmBody: 'Le mode Watched basculera sur l’autre liste si elle est encore liée.',
  listOperationPending: 'Une opération sur les listes est déjà en cours.',
  listServerOffline: 'Pas de connexion au serveur. Vérifie que le serveur local tourne.',
  listServerTimeout: 'Le serveur ne répond pas. Réessaie dans un instant.',
  listGenericError: 'Impossible de mettre à jour la liste.',
  listOperationSuccess: {
    link: (provider: string) => `${provider} est lié et devient la source active.`,
    set_active: (provider: string) => `${provider} est maintenant la source active.`,
    refresh: (provider: string) => `${provider} a été synchronisé.`,
    unlink: (provider: string) => `${provider} a été délié.`,
  },
  listLastSync: (when: string) => `Dernière sync : ${when}`,
  listNeverSynced: 'Jamais synchronisé',
  listState: {
    idle: 'État non vérifié',
    ok: 'À jour',
    cache: 'Cache',
    stale: 'Liste potentiellement périmée',
    private_empty: 'Liste vide ou privée',
    unavailable: 'Indisponible',
    unlinked: 'Non lié',
  },
  signInForAccount: 'Connectez-vous pour gérer confidentialité, blocages et listes',
} as const;
