import type {
  SuggestionCategory,
  SuggestionCorrectionField,
  SuggestionStatus,
} from '@aniquizz/shared';

export const SUGGESTION_CATEGORY_LABELS: Record<SuggestionCategory, string> = {
  IMPROVEMENT: 'Amélioration',
  SONG_REQUEST: 'Son souhaité',
  CORRECTION: 'Correction',
  OTHER: 'Autre',
};

export const SUGGESTION_STATUS_LABELS: Record<SuggestionStatus, string> = {
  OPEN: 'En cours',
  PLANNED: 'Prévue',
  DONE: 'Réalisée',
  REJECTED: 'Refusée',
};

export const SUGGESTION_CORRECTION_LABELS: Record<SuggestionCorrectionField, string> = {
  TITLE: 'Titre',
  ARTIST: 'Artiste',
  DIFFICULTY: 'Difficulté',
  OTHER: 'Autre donnée',
};

export const SUGGESTIONS_COPY = {
  title: 'La boîte à idées',
  subtitle:
    'Proposez un son, signalez une erreur ou imaginez la prochaine amélioration d’AniQuizz.',
  create: 'Proposer une idée',
  duplicateHint:
    'Avant de publier, recherchez quelques mots-clés sur le board pour vérifier que l’idée n’existe pas déjà.',
  postingLimit: 'Maximum 5 suggestions par période glissante de 24 heures.',
  top: 'Les plus soutenues',
  recent: 'Les plus récentes',
  allCategories: 'Toutes les catégories',
  allStatuses: 'Tous les statuts',
  empty: 'Aucune suggestion ici pour le moment.',
  emptyAction: 'Lancez la première idée.',
  teamReply: 'Réponse de l’équipe',
  vote: 'Soutenir cette suggestion',
  unvote: 'Retirer mon soutien',
  loginToVote: 'Connectez-vous pour soutenir une idée.',
  createSuccess: 'Suggestion publiée.',
  voteError: 'Impossible de mettre à jour votre vote.',
  loadError: 'Impossible de charger les suggestions.',
  delete: 'Supprimer',
  deleteSuccess: 'Suggestion supprimée.',
  deleteError: 'Suppression impossible.',
  deleteConfirm: 'Supprimer définitivement cette suggestion ?',
  backHome: 'Retour à l’accueil',
  searchPlaceholder: 'Rechercher une idée, un son, un anime…',
  searchAria: 'Rechercher dans les suggestions',
  clearSearchAria: 'Effacer la recherche',
  filterCategoryAria: 'Filtrer par catégorie',
  filterStatusAria: 'Filtrer par statut',
  previousPage: 'Précédent',
  nextPage: 'Suivant',
  loadingAria: 'Chargement',
  votes: 'votes',
  readMore: 'Lire la suite',
  readLess: 'Réduire',
  anonymousAuthor: 'Compte supprimé',
  pageStatus: (page: number, total: number) => `Page ${page} sur ${total}`,
  createTitle: 'Proposer une idée',
  createDescription: 'Une idée claire et précise a plus de chances d’être soutenue.',
  categoryLegend: 'Catégorie',
  titleLabel: 'Titre',
  titlePlaceholder: 'Résumez votre idée en une phrase',
  bodyLabel: 'Détails',
  bodyPlaceholder: 'Expliquez le problème, votre idée ou le son que vous aimeriez retrouver…',
  songLabel: 'Son concerné',
  changeSong: 'Changer',
  songSearchPlaceholder: 'Rechercher un titre ou un anime…',
  songSearchAria: 'Rechercher un son du catalogue',
  songListAria: 'Résultats de recherche de sons',
  searching: 'Recherche…',
  noSongs: (query: string) => `Aucun son trouvé pour « ${query} ».`,
  loadMoreSongs: 'Afficher plus',
  songSearchError: 'Impossible de rechercher le catalogue.',
  correctionFieldLabel: 'Champ à corriger',
  proposedValueLabel: 'Valeur proposée',
  chooseDifficulty: 'Choisir une difficulté',
  proposedPlaceholder: 'Nouvelle valeur',
  cancel: 'Annuler',
  publish: 'Publier',
  readyToPublish: 'Prêt à publier.',
  createError: 'Impossible de publier cette suggestion.',
  titleTooShort: 'Le titre doit contenir au moins 4 caractères.',
  bodyTooShort: 'Les détails doivent contenir au moins 10 caractères.',
  songRequired: 'Sélectionnez le son concerné.',
  proposedRequired: 'Choisissez ou saisissez la valeur proposée.',
  adminTitle: 'Suggestions',
  adminSubtitle: 'Triez les retours, publiez une réponse officielle et suivez leur avancement.',
  adminRefresh: 'Actualiser',
  adminStatus: 'Statut',
  adminReplyLabel: 'Réponse de l’équipe',
  adminReplyPlaceholder: 'Réponse publique facultative…',
  adminSave: 'Enregistrer',
  adminDeleteAria: 'Supprimer la suggestion',
  adminEmpty: 'Aucune suggestion pour ces filtres.',
  adminDeleteConfirm: 'Supprimer définitivement cette suggestion et ses votes ?',
  adminUpdateSuccess: 'Suggestion mise à jour.',
  adminUpdateError: 'Mise à jour impossible.',
  adminDeleteSuccess: 'Suggestion supprimée.',
  adminDeleteError: 'Suppression impossible.',
  adminLoadError: 'Chargement des suggestions impossible.',
} as const;
