/** French UI copy for the profile page (i18n-ready). Vousvoiement throughout. */

export const PROFILE_COPY = {
  favoriteSongsTitle: 'Titres favoris',
  favoriteSongsEmptyOwn: 'Aucun titre favori pour le moment.',
  favoriteSongsEmptyOwnHint:
    'Likez des sons depuis la librairie ou à la révélation en fin de manche.',
  favoriteSongsEmptyPublic: (username: string) => `${username} n'a pas encore de titres favoris.`,
  favoriteSongsCount: (n: number) =>
    n === 0 ? 'aucun favori' : n === 1 ? '1 favori' : `${n.toLocaleString('fr-FR')} favoris`,
  favoriteSongsShownTotal: (shown: number, total: number) =>
    `${shown.toLocaleString('fr-FR')} affiché${shown > 1 ? 's' : ''} · ${total.toLocaleString('fr-FR')} au total`,
  favoriteSongsViewAll: 'Voir tout',
  favoriteSongsBrowseLibrary: 'Explorer la librairie',
  favoriteSongsLoadError: 'Impossible de charger les titres favoris.',
  favoriteSongsOpenSong: (title: string) => `Voir les détails — ${title}`,
  favoriteSongsCustomize: 'Choisir mes favoris',
  favoriteSongsCuratedBadge: 'Sélection perso',
  customizeTitle: 'Mes 5 favoris du profil',
  customizeHint:
    "Choisissez jusqu'à 5 titres parmi vos favoris à mettre en avant sur votre profil public.",
  customizeSelected: (n: number, max: number) => `${n}/${max} sélectionnés`,
  customizeSearch: 'Rechercher dans vos favoris…',
  customizeSave: 'Enregistrer',
  customizeCancel: 'Annuler',
  customizeReset: 'Tout afficher',
  customizeResetHint: 'Réaffiche vos favoris les plus récents sans sélection personnalisée.',
  customizeSavedToast: 'Favoris du profil mis à jour',
  customizeErrorToast: 'Impossible de mettre à jour vos favoris du profil.',
  customizeEmptyLikes: 'Likez des sons depuis la librairie pour pouvoir les sélectionner ici.',
  customizeMaxReached: (max: number) => `Vous ne pouvez sélectionner que ${max} titres maximum.`,
  customizeOrderTitle: 'Ordre sur le profil',
  customizeOrderHint: "Utilisez les flèches pour définir l'ordre d'affichage (1 = en haut).",
  customizeNoneSelected: 'Aucun titre sélectionné — ajoutez-en depuis la liste ci-dessous.',
  customizeAddTitle: 'Ajouter depuis vos favoris',
  customizeBrowseTotal: (n: number) =>
    n === 1 ? '1 favori' : `${n.toLocaleString('fr-FR')} favoris`,
  customizeBrowseEmpty: 'Aucun favori à ajouter sur cette page.',
  customizePage: (page: number, total: number) => `Page ${page} / ${total}`,
  customizePrevPage: 'Précédent',
  customizeNextPage: 'Suivant',
  favoriteSongsPublicToggle: 'Favoris public',
  favoriteSongsPublicHidden: 'Masqué aux autres joueurs',
  favoriteSongsHiddenBadge: 'Masqué',
  seoUnavailable: 'Profil indisponible',
  unavailableTitle: 'Profil indisponible',
  unavailableBody: 'Ce profil n’est pas accessible.',
  loadFailedTitle: 'Impossible de charger le profil',
  sessionStillActive: 'Votre session est toujours active. Réessayez dans un instant.',
  retry: 'Réessayer',
  backHome: "Retour à l'accueil",
  backToOwnProfile: 'Retour à mon profil',
  backToAdmin: "Retour à l'administration",
  updatedToast: 'Profil mis à jour !',
  genericErrorToast: 'Une erreur est survenue',
  uploadError: 'Erreur upload',
  cropError: 'Erreur lors du recadrage',
  imageTooLarge: "L'image est trop volumineuse (Max 5 Mo)",
  pokedexTitle: 'Pokédex Musical',
  uniqueDiscovered: 'Sons uniques découverts',
  unranked: 'Non classé',
  availableTotal: (n: number) => `Total disponible : ${n}`,
  achievementsTitle: 'Succès',
  achievementsSoonTitle: 'Bientôt disponible',
  achievementsSoonBody: 'Une collection de succès illustrés arrive prochainement.',
  historyTitle: 'Historique de parties',
  historyPrivate: 'L’historique récent de ce joueur est privé.',
  historyEmpty: "Aucune partie jouée pour l'instant.",
  memberSince: (when: string) => `Membre depuis ${when}`,
  online: 'En ligne',
  addFriend: 'Ajouter en ami',
  block: 'Bloquer',
  acceptRequest: 'Accepter la demande',
  requestSent: 'Demande envoyée',
  removeFriend: 'Retirer',
  unblock: 'Débloquer',
  editUsername: 'Modifier le pseudo',
  saveUsername: 'Enregistrer le pseudo',
  cancelUsername: 'Annuler la modification du pseudo',
  editAvatar: (username: string) => `Modifier l'avatar de ${username}`,
  profileActions: 'Actions du profil',
  changePassword: 'Changer de mot de passe',
  signOut: 'Déconnexion',
  deleteAccount: 'Supprimer mon compte',
  xpIntoLevel: (into: number, next: number) => `${into} / ${next} XP`,
  levelMax: 'Niveau max',
  deleteTitle: 'Supprimer mon compte',
  deleteBody:
    'Cette action est définitive et irréversible. Seront supprimés : votre profil, vos statistiques, votre historique de parties, votre liste AniList liée et vos liens d’amitié.',
  deleteConfirmLead: 'Saisissez votre pseudo',
  deleteConfirmTrail: 'pour confirmer',
  deleteTimeout: 'Délai dépassé. Réessayez.',
  deleteFailed: 'Impossible de supprimer le compte.',
  deleteWrongPassword: 'Mot de passe incorrect.',
  deleteSuccess: 'Compte supprimé.',
  deleteSubmit: 'Supprimer définitivement',
  deleteCancel: 'Annuler',
  watchlistAnilistTitle: 'Lier AniList',
  watchlistAnilistPlaceholder: 'Votre pseudo AniList exact...',
  watchlistAnilistHint:
    "Utilisez le pseudo de l'URL du profil (anilist.co/user/...), pas le nom affiché.",
  watchlistMalTitle: 'Lier MyAnimeList',
  watchlistMalPlaceholder: 'Votre pseudo MyAnimeList exact...',
  watchlistMalHint:
    "Utilisez le pseudo de l'URL du profil (myanimelist.net/profile/...), pas le nom affiché.",
  watchlistUsernameLabel: 'Pseudo',
  watchlistSave: 'Sauvegarder',
  watchlistSaving: 'Liaison...',
} as const;
