export const DAILY_COPY = {
  title: 'Quiz du jour',
  titleLead: 'Quiz du',
  titleAccent: 'jour',
  playCta: 'Commencer',
  loginCta: 'Connexion requise',
  doneCta: 'Voir le résultat',
  settlingCta: 'Tentative en cours…',
  unavailable: "Le quiz du jour n'est pas encore prêt.",
  confirmTitle: 'Une seule tentative',
  confirmBody:
    '5 manches, 15 secondes pour répondre à chacune. Chaque extrait démarre à un moment aléatoire du son. Ne quittez pas en cours de route : si vous coupez, les questions restantes sont fausses et la tentative est terminée.',
  cancel: 'Annuler',
  forfeit: 'Abandonner',
  leaveTitle: 'Quitter le défi ?',
  leaveBody: 'Les questions restantes seront comptées fausses et la tentative sera terminée.',
  victory: 'Victoire',
  defeat: 'Défaite',
  detailTitle: 'Détail de la partie',
  seeRoundDetail: 'Voir le détail des rounds',
  backToDaily: 'Retour',
  modeRail: 'JOUR',
  streak: 'Série',
  time: 'Temps',
  timeCumulative: 'cumulé',
  leaderboard: 'Classement du jour',
  leaderboardUnavailable: 'Classement indisponible.',
  leaderboardEmpty: 'Personne n’a encore terminé aujourd’hui.',
  participants: 'participants',
  resetsIn: 'Réinitialisation dans',
} as const;
