/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 7a899346723fd6b6af863a3060f2cdba)
interface __BaseEnv_Env {
	MEDIA: R2Bucket;
	CORS_ORIGIN: "https://aniquizz.com,https://www.aniquizz.com,http://localhost:8080,http://localhost:8083";
	MEDIA_PLAYBACK_SECRET: string;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "CORS_ORIGIN" | "MEDIA_PLAYBACK_SECRET">> {}
}
