import type { NewsItem } from './newsTypes';

/** Generated by `pnpm --filter aniquizz-client sync:news` from newsData.ts. Do not edit. */
export type NewsPreviewItem = Omit<NewsItem, 'content'>;

export const latestNewsPreview: NewsPreviewItem[] = [
  {
    id: 8,
    title: 'Mise à jour v26.6 - Quiz du jour, Paramètres, Précision Artiste & Soutenir',
    description:
      'Défi quotidien, paramètres joueur, précision Artiste, bouton Soutenir, et un passage catalogue.',
    date: '2026-09-14T12:00:00Z',
    type: 'update',
  },
  {
    id: 7,
    title: 'Mise à jour v26.5 - Endings & Playlists',
    description: 'Plus de 1800 endings ajoutés, playlists thématiques (shonen, seinen, décennies…)',
    date: '2026-09-11T17:00:00Z',
    type: 'update',
  },
];
